# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('tags', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'image_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagePath',
            fields=[
                ('md5', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('path', models.ImageField(default='/tmp/none.jpg', upload_to=b'uploads')),
            ],
            options={
                'db_table': 'image_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('counter', models.IntegerField()),
            ],
            options={
                'db_table': 'image_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'image_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
